diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Sublime Text\\subl.exe" -w
pull.rebase=false
init.defaultbranch=main
user.name=Zinaida Knyazeva
user.email=Z9191593080@yandex.ru
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@github.com:ZinaidaK13/Sprint_4.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
